ATBM60XX_VERSION = master
ATBM60XX_SITE = https://github.com
ATBM60XX_SITE_METHOD = git
ATBM60XX_DEPENDENCIES = linux

ifeq ($(BR2_PACKAGE_ATBM60XX_MODEL_601X),y)
ATBM60XX_MODULE_OPTS += CONFIG_ATBM603X=y
endif
ifeq ($(BR2_PACKAGE_ATBM60XX_MODEL_602X),y)
ATBM60XX_MODULE_OPTS += CONFIG_ATBM602X=y
endif

ifeq ($(BR2_PACKAGE_ATBM60XX_INTERFACE_USB),y)
ATBM60XX_MODULE_OPTS += CONFIG_ATBM_USB_BUS=y
else ifeq ($(BR2_PACKAGE_ATBM60XX_INTERFACE_SDIO),y)
ATBM60XX_MODULE_OPTS += CONFIG_ATBM_SDIO_BUS=y
endif

define ATBM60XX_BUILD_CMDS
	$(MAKE) -C $(LINUX_DIR) M=$(@D) $(LINUX_MAKE_FLAGS) $(ATBM60XX_MODULE_OPTS) modules
enddefine

define ATBM60XX_INSTALL_TARGET_CMDS
	$(MAKE) -C $(LINUX_DIR) M=$(@D) $(LINUX_MAKE_FLAGS) $(ATBM60XX_MODULE_OPTS) modules_install
enddefine

$(eval $(generic-package))
